#!/bin/bash

dropdb -H $POSTGIS_PORT_5432_TCP_ADDR -U docker docker
createdb -H $POSTGIS_PORT_5432_TCP_ADDR -U docker docker
psql -H $POSTGIS_PORT_5432_TCP_ADDR -U docker <<END
create extension postgis;
END

python manage.py syncdb --noinput
python manage.py migrate