#!/bin/bash

mkdir /tmp/media
pushd $PWD > /dev/null
cp $1 /tmp
cd /tmp
tar -xzf "$1" 
cd media
rsync -avh --rsh="ssh -p 1338" /tmp/media docker@192.168.59.103:/home/docker/hydroshare/static
popd
rm -rf /tmp/media

