#!/bin/bash

if [[ $PWD == *hydroshare ]] 
then

docker run -t -i -name hydroshare-dev \
      -link hydroshare-redis:redis \
      -link hydroshare-postgis:postgis \
      -p 0.0.0.0:80:80 -expose 22 \
      -v $PWD:/home/docker/hydroshare
      dev.hydroshare.org:5999/hydroshare /bin/bash

else
  echo "ERROR: Must start container from the hydroshare git repository root."
fi
