#!/bin/bash

APP=$1

if [ -d "$PWD/$APP/migrations" ]; then
  ssh -p 1338 docker@localhost "cd hydroshare; python manage.py schemamigration --auto $APP && python manage.py migrate $APP"
  rsync -avh --rsh='ssh -p 1338' docker@localhost:/home/docker/hydroshare/$APP/migrations $PWD/$APP
  pushd $PWD
  cd $APP
  git add migrations
  popd
else
  ssh -p 1338 docker@localhost "cd hydroshare; python manage.py schemamigration --init $APP && python manage.py migrate $APP"
  mkdir $PWD/$APP/migrations
  rsync -avh --rsh='ssh -p 1338' docker@localhost:/home/docker/hydroshare/$APP/migrations $PWD/$APP
  pushd $PWD
  cd $APP
  git add migrations
  popd
fi
